/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteImport } from './routes/post'
import { Route as PasswordManagerRouteImport } from './routes/password-manager'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DigitalFootprintRouteImport } from './routes/digital-footprint'
import { Route as CreatePostRouteImport } from './routes/create-post'
import { Route as IndexRouteImport } from './routes/index'

const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordManagerRoute = PasswordManagerRouteImport.update({
  id: '/password-manager',
  path: '/password-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalFootprintRoute = DigitalFootprintRouteImport.update({
  id: '/digital-footprint',
  path: '/digital-footprint',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePostRoute = CreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-post': typeof CreatePostRoute
  '/digital-footprint': typeof DigitalFootprintRoute
  '/knowledge': typeof KnowledgeRoute
  '/notes': typeof NotesRoute
  '/password-manager': typeof PasswordManagerRoute
  '/post': typeof PostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-post': typeof CreatePostRoute
  '/digital-footprint': typeof DigitalFootprintRoute
  '/knowledge': typeof KnowledgeRoute
  '/notes': typeof NotesRoute
  '/password-manager': typeof PasswordManagerRoute
  '/post': typeof PostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-post': typeof CreatePostRoute
  '/digital-footprint': typeof DigitalFootprintRoute
  '/knowledge': typeof KnowledgeRoute
  '/notes': typeof NotesRoute
  '/password-manager': typeof PasswordManagerRoute
  '/post': typeof PostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-post'
    | '/digital-footprint'
    | '/knowledge'
    | '/notes'
    | '/password-manager'
    | '/post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-post'
    | '/digital-footprint'
    | '/knowledge'
    | '/notes'
    | '/password-manager'
    | '/post'
  id:
    | '__root__'
    | '/'
    | '/create-post'
    | '/digital-footprint'
    | '/knowledge'
    | '/notes'
    | '/password-manager'
    | '/post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePostRoute: typeof CreatePostRoute
  DigitalFootprintRoute: typeof DigitalFootprintRoute
  KnowledgeRoute: typeof KnowledgeRoute
  NotesRoute: typeof NotesRoute
  PasswordManagerRoute: typeof PasswordManagerRoute
  PostRoute: typeof PostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-manager': {
      id: '/password-manager'
      path: '/password-manager'
      fullPath: '/password-manager'
      preLoaderRoute: typeof PasswordManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-footprint': {
      id: '/digital-footprint'
      path: '/digital-footprint'
      fullPath: '/digital-footprint'
      preLoaderRoute: typeof DigitalFootprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-post': {
      id: '/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof CreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePostRoute: CreatePostRoute,
  DigitalFootprintRoute: DigitalFootprintRoute,
  KnowledgeRoute: KnowledgeRoute,
  NotesRoute: NotesRoute,
  PasswordManagerRoute: PasswordManagerRoute,
  PostRoute: PostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
